### ISSUE TITLE
0.60.x Discussion

### ISSUE THREAD

**Issue by grabbou** [react-native-community/releases#116]
0.60.0-rc.0 is most likely going to be released tomorrow. The branch is already cut. We are working on the changelog.

Stay tuned.

**Comment by radeno** [comment]
@grabbou I think better timing for cut first RC should be next week. Easter holidays are behind door and many developers will not work. Even first RC-0 will be as fresh as possible.

**Comment by rhdeck** [comment]
Was the delay monday decided? Or is the drop happening today (Friday)? Looking to test the hot new autolinking.

**Comment by turnrye** [comment]
@rhdeck yes, we're delaying the publish til Monday. We'll have a WIP changelog today, though it'll still need a lot of refinement.

**Comment by grabbou** [comment]
Yes. The release is ready to go and tests are passing. I wanted to wait for the changelog because the amount of changes is quite big and we want to wrap it up on the CLI side too.

**Comment by Vyazovoy** [comment]
Any chances it will be published this week?

**Comment by piashcse** [comment]
is there any possibility to release 0.60-rc0  by next week?

**Comment by grabbou** [comment]
Yes, the plan is to release it this week, ideally before Wednesday. We are
still waiting for one CLI issue to be fixed, others have been already
resolved.

**Comment by grabbou** [comment]
0.60 is currently blocked due to CocoaPods integration. We have recently migrated default template to CocoaPods but want to avoid users running `pod install` after `react-native init`.

Our work can be tracked here: https://github.com/facebook/react-native/pull/24638, tho we are hitting blocker after blocker.

Heading off to holidays, will be back on Monday and that's most likely when I resume my work on the CLI where additional support has to be added.

**Comment by jeveloper** [comment]
Hope you have a great holiday man , good for you @grabbou

**Comment by Salakar** [comment]
Any chance we could cherry pick these two small commits:

- https://github.com/facebook/react-native/commit/bdb1d4377e47c6cd49ff619134d4860519a3cb0c
- https://github.com/facebook/react-native/commit/88dbb4558cd10f129f2c31e3b0b872924aba5416

**Comment by mikehardy** [comment]
@Salakar - I don't think 0.60 is cut yet, so that comment might best be on 0.59.x for cherry pick?

**Comment by sunnylqm** [comment]
@mikehardy Already cut and was planned to publish last week https://github.com/facebook/react-native/commits/0.60-stable

**Comment by grabbou** [comment]
Yes. I can include them too once we are done with the CocoaPods issue.

Update: Unfortunately, the approach in facebook/react-native#24638 ended up being a dead end. We will be running `pod install` on the client side (meaning you need to have CocoaPods pre-installed).

We are going to implement this ticket https://github.com/react-native-community/cli/issues/368 and we will ship 0.60 as soon as it's resolved.

Unfortunately, given the amount of things to coordinate for 0.60, I can't give you any promises. I will try to do my best to ship it as soon as possible tho.

**Comment by jsamr** [comment]
Please cherry-pick [facebook/react-native@`c5c79e5`](https://github.com/facebook/react-native/commit/c5c79e5d718ad0777e014dd8c1e8d398d8172f3d) which prevent a memory leak on iOS!

**Comment by jsamr** [comment]
And it would be marvelous if we had font family support in Android, which has just been merged into master [facebook/react-native@`fd6386a`](https://github.com/facebook/react-native/commit/fd6386a07eb75a8ec16b1384a3e5827dea520b64). This PR makes [Android xml font declarations](https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml) operable within the React Native framework.

Basically, it means that you can have mixed nested font styles for custom fonts (`fontFamily`, `fontStyle` and `fontWeight`) without the need to use postscript font name such as `OpenSans-Bold`).

**Comment by danilobuerger** [comment]
Is 0.60 going to be recut? If not, please cherry pick 

* [Android] [Fixed] - LayoutAnimations cause invalid view operations facebook/react-native@20b4879
and its dependent commits.

(This was already requested for 0.59.5, but couldn't be cherry picked because of a dependent commit)

**Comment by radeno** [comment]
I agree with @danilobuerger about recutting new RC0. 22 days from first recut is long time. Many fine bugfixes and some new improvements are very promising to have in first release candidate. But i don't know how much time it takes and how much new problems and issues will appear after merging commits.

**Comment by jinshin1013** [comment]
Can we also cherry pick this if it's not too late?:
- [iOS] Fixes tintColor not changing on Gif image on iOS [facebook/react-native@`75380aa`](https://github.com/facebook/react-native/commit/75380aa3296210777dc0be70a722701767276117)

**Comment by grabbou** [comment]
We will look into re-cutting 0.60 before making the first release. Depending on the tests and stability, we may or may not do it.

I will update you in this issue. Meanwhile, please wait a bit with suggesting cherry-picks until you give the first release a go.

**Comment by rhdeck** [comment]
Is there a new timeframe? We're four weeks past "most likely going to be released tomorrow." We all know things take time, but would help my dev efforts to have a rough undertstanding of when this would be pre-release, but on npm.

**Comment by grabbou** [comment]
Unfortunately, no time frame. We are working on it all the time. I will
give you an update in two days, where we should have a better overview.

**Comment by kelset** [comment]
> Is there a new timeframe? We're four weeks past "most likely going to be released tomorrow."

As Mike said, we are doing what we can to get to the point where we can produce a stable 0.60 first RC.

Also, as we communicated here some time ago -> https://github.com/react-native-community/discussions-and-proposals/issues/17#issuecomment-475397553 we are changing a bit the approach to releases so that they are "more distant" from each other, and more "meaty", in a way. This ofc can lead to complexities on the road, which are hard to detect ahead of time.

**Comment by Nehal-29** [comment]
> facebook/react-native@`c5c79e5`

are we getting a fix related to memory leak in 0.60 version. Really need it.

**Comment by rhdeck** [comment]
Hi, poking my hand up only because @grabbou mentioned maybe knowing more a week ago, and if so, would be great to understand. Have native components I would love to build centered on the new systems in 0.60. 

If no news, so be it. 

And if there is any context that would let me or others on thread help, all the better!

**Comment by grabbou** [comment]
@rhdeck the release is literally now on CircleCI. I'll post an update in 5 minutes or something.

**Comment by fjtrujy** [comment]
Hello guys,
I'm right now having several issues trying to have the RN 0.6.0.x project with frameworks in the pod file.

So far I see some imports that are wrong.

Do you know if 0.60 is going to support the use of frameworks & Cocoapod ?

This is my current podfile

```
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'RNUpgrade' do
  # Pods for HelloWorld
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'RNUpgradeTests' do
      inherit! :search_paths
      # Pods for testing
  end
  
end
```

Thanks.

**Comment by Frekansapp** [comment]
Hi, 0.60.0-rc.0 version when will I come to npm? Can't wait to use 😃

**Comment by kelset** [comment]
hey everyone - sorry, we are still having issues with the release pipeline.

We are facing an issue with Detox (which *may* be fixed, we are testing cherry picking some commits) and one with Buck, where we are waiting from some feedback from the FB side on how to fix.

We should be close, sorry but there are issues that keep popping out lately 😓

**Comment by kelset** [comment]
Allright, 0.60 RC0 is finally out!

https://github.com/facebook/react-native/releases/tag/v0.60.0-rc.0

Please test it and let us know if you find any major issues!
Best way to report them would be to open an issue in the main repo, add in front of the title [0.60 RC] and then link it here 🤗

**Comment by Kennytian** [comment]
@kelset 
`
✨  Done in 9.76s.
info Installing required CocoaPods dependencies
`
run `react-native init RN060 --version react-native@next`， initial project block on `CocoaPods installing` here 5 mins

**Comment by peterlazar1993** [comment]
If you haven't setup CocoaPods before, the initial setup can take some time.

**Comment by eshikerya** [comment]
have no way to upgrade:
```
$ react-native upgrade 0.60.0-rc.0
info Fetching diff between v0.59.8 and v0.60.0-rc.0...
error Failed to fetch diff for react-native@0.60.0-rc.0. Maybe it's not released yet?
```
```react-native-git-upgrade``` fails with message:
```
git-upgrade info Generate old version template 
git-upgrade ERR! An error occurred during upgrade: 
git-upgrade ERR! Error: Cannot find module '/Users/***/node_modules/react-native/local-cli/generator/copyProjectTemplateAndReplace'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at runCopyAndReplace (/Users/***/.config/yarn/global/node_modules/react-native-git-upgrade/cliEntry.js:163:32)
    at generateTemplates (/Users/***/.config/yarn/global/node_modules/react-native-git-upgrade/cliEntry.js:151:12)
    at Object.<anonymous> (/Users/***/.config/yarn/global/node_modules/react-native-git-upgrade/cliEntry.js:288:11)
    at Generator.next (<anonymous>)
    at step (/Users/***/.config/yarn/global/node_modules/react-native-git-upgrade/cliEntry.js:171:191)
    at /Users/***/.config/yarn/global/node_modules/react-native-git-upgrade/cliEntry.js:171:361
    at tryCallOne (/Users/***/.config/yarn/global/node_modules/promise/lib/core.js:37:12)
    at /Users/***/.config/yarn/global/node_modules/promise/lib/core.js:123:15 
```

any way to fix it?

**Comment by mikehardy** [comment]
I like the new example app page a lot. But...I thought it was for react-**native** 🤔 😆 
<img width="375" alt="Screen Region 2019-05-30 at 11 56 10" src="https://user-images.githubusercontent.com/782704/58649624-2e1e6e00-82d2-11e9-919b-d93cb2fd2db8.png">

**Comment by mikehardy** [comment]
So, I maintain react-native-device-info, and I am really excited to see how it goes with RN060

but if I do
```shell
react-native init RN060 --version react-native@next
cd RN060/
npm i react-native-device-info
npx react-native run-android
```

it hangs in gradle on "Evaluating settings"
Ok, so maybe I forgot to link (but auto-linking?), so after doing `react-native link react-native-device-info` it still hangs in gradle on evaluating settings

I was fully expecting it to fail on AndroidX transition, but Evaluating settings was unexpected.

So maybe it just was the package, I tried it fresh:

```shell
react-native init RN060 --version react-native@next
npx react-native run-android
npx react-native start
```

Now, I definitely forgot to start the packager before the app started, so it gave me the error screen "packager not running etc" when it couldn't download the bundle. Totally okay. But then after I started metro and hit reload...

I get a blank white screen in android emulator API28, when I go to investigate with `npx react-native log-android` I get:

```
(virtualenv) mike@kunashir:~/work/react-random/RN060 % npx react-native log-android
info Starting logkitty
error Cannot read property 'VERBOSE' of undefined. Run CLI with --verbose flag for more details.
```

Which is all unexpected...

If I kill the app and run it again, the example app shows up (but on a Pixel 2 emulator at least it shows "Welcome to React" (vs React-Native) similar to my screenshot above from iPhone X simulator)


Anyone have successful android builds with this and any modules installed? 

Anyone else see what I saw on android if you don't have the packager running at first then reload?

**Comment by kelset** [comment]
hey everyone, as I mentioned earlier can you please create dedicated issues in the main repo and link them here instead of writing the thing directly - it's makes it harder for me to keep the issue in topic 😅

re:

@eshikerya at the moment you shouldn't try to do the upgrade, only to test it via apps - AFAIK we won't produce a diff for the RC. Also, `react-native-git-upgrade` is no-op now, so you should not be using it. Sorry if it wasn't communicated properly.

@mikehardy 
1. yes, but React & React Native should be the part of the same community, don't they? ;) 

2. there is a PR pending for the CLI, you may need to test after it gets merged: https://github.com/facebook/react-native/pull/25094

**Comment by mikehardy** [comment]
I will log dedicated issues if these are confirmed problems, but thought for the immediately excited testers I might hear whether it's just something stupid I did or not ;-). I was curious if anyone else had android success before I invested the time with issues and PRs etc etc

**Comment by eshikerya** [comment]
@kelset tried ```react-native-git-upgrade```as fallback to test the ways I could upgrade.
thank you for clarification. any estimate when we would be able to upgrade?
AFAIK 0.60 contain a fix our project require, split-view fixes for iOS and Android(app reload when view changed the size)

**Comment by MohamadKh75** [comment]
Crashes on Android....

https://github.com/facebook/react-native/issues/25096

**Comment by sunnylqm** [comment]
Fix for memory leak in fetch for android
https://github.com/facebook/react-native/commit/bccc92dfdd2d85933f2a9cb5c8d1773affb7acba
https://github.com/facebook/react-native/commit/a4f7e17a4f06ee713fecbfa1fbb1e632a9d3bf89

**Comment by fungilation** [comment]
An important one with fetch. Noob question: Will these merged PRs land on next 0.60 rcs and stable?

**Comment by kelset** [comment]
they landed on master, we will cherry pick for next RC most likely

**Comment by DoisLucas** [comment]
Good work guys, I'm very excited to test this new release.

**Comment by IljaDaderko** [comment]
Perhaps a bit of a naive question, but for those of us who were using cocoapods before, besides changing how we include react pods / adding jsi ones, is it safe to continue using third party deps without autolinking? i.e. if I have manually included paths to their podspecs and all that?~

**Comment by immortalx** [comment]
Does autolinking needs any flag or its already enabled?
To install react-native-gesture-handler for example i needed to run react-native link, it added a line to my podfile and i needed to run pod install inside the ios directory. 

Is this how it's supposed to be?

**Comment by matt-oakes** [comment]
@IljaDaderko @immortalx It's an opt-in feature on both platforms. For iOS you need to add these two lines to your `ios/Podfile`: https://github.com/facebook/react-native/commit/261197d85705dad1a362cc4637aa308c0382dcbe#diff-a3c6c8e64fbbd1efef345c45e3811571

Note that these are currently not in the template `Podfile` due to an issue with the E2E CI tests.

**Comment by dishantwalia** [comment]
Crash on some android devices with 64 bit support JSC #https://github.com/facebook/react-native/issues/24261

**Comment by kelset** [comment]
@MohamadKh75 @dishantwalia that crash wasn't caused by 0.60 RC, so for the purpose of this issue it's not really related. Also, it seems to be connected to the JSC.

**Comment by kelset** [comment]
about autolinking:

@IljaDaderko 
> , is it safe to continue using third party deps without autolinking? i.e. if I have manually included paths to their podspecs?

yes, AFAIK - thee autolinking is simply meant to having you not doing those steps.

@immortalx 
I'm not sure I understand - you created a new 0.60 RC project and you had to manually run `react-native link`? Ideally, it should automatically run when you do the `yarn add`. But I'm not sure that it's still feature-complete, hence why it's still in beta in the highlights.

**Comment by mjmasn** [comment]
Minor fix for the cherry-pick list https://github.com/facebook/react-native/commit/b45d3b8697c6ed2ce5c6e4eac7bfd14553c79ed8

**Comment by kelset** [comment]
@eshikerya we published the diff for [0.60RC](https://github.com/react-native-community/rn-diff-purge/compare/release/0.59.8..release/0.60.0-rc.0), so if you want to try again the upgrade command from the CLI it **should** work this time - but again, it's only an RC so be careful to upgrade only test projects/on safe branches so that you can always reverse without troubles.

**Comment by immortalx** [comment]
@matt-oakes thank you, it's worked on IOS really well with most of the packages i tested. Autolinking is just for IOS while in beta or android should be working as well?

**Comment by mikehardy** [comment]
@immortalx assuming it is working (it is in beta), autolinking works for both platforms

**Comment by matt-oakes** [comment]
@immortalx Sorry, I should have linked the Android changes too:

* https://github.com/facebook/react-native/blob/7f489b63f201f65158d58ad5fe33f460938d0c74/template/android/settings.gradle#L2
* https://github.com/facebook/react-native/blob/7f489b63f201f65158d58ad5fe33f460938d0c74/template/android/app/build.gradle#L185

**Comment by immortalx** [comment]
@matt-oakes @mikehardy thank you. The linking part seems to be working but all packages  fail with a similar error, for example:

Execution failed for task ':react-native-screens:compileDebugJavaWithJavac'.

Doesn't seem to be related to linking itself, maybe they are not updated to work with 0.60 yet.

**Comment by yurykorzun** [comment]
I am a bit concerned the way podspecs were split up. We self host all of RN podspecs in our own repo, and now most of them have relative paths to their folder. We will need to replace the source_files prop to reference the full path in our publishing script. Obviously, most projects install RN into XCode from a local node_modules folder, so it's not going to be problem for most people. It's just in our project we install everything RN related using cocoapods into an existing project.

**Comment by mikehardy** [comment]
@immortalx yeah, owing to the problems I had immediately (https://github.com/react-native-community/releases/issues/116#issuecomment-497409523) I said to myself "yeah, it isn't ready yet" and even though I maintain one of the most used libraries I couldn't get it to work out of the box. So your guess is likely right

**Comment by mikehardy** [comment]
For people wanting to test RN 0.60 that are having issues with android dependencies, and especially for library maintainers, @rozPierog made a gradle script that will generate 2 android "AAR" files (Android ARchive) that can serve as library dependencies in your project. One de-jetified and one AndroidX. So you can convert a library dependency to AndroidX and it will still be compatible with RN0.59 (non-AndroidX) apps. If you want to help test or collaborate you would be more than welcome, convert your library to AndroidX for RN0.60 then try this for RN0.59+RN0.60: https://github.com/react-native-community/discussions-and-proposals/issues/129#issuecomment-498740388 :-)

**Comment by kelset** [comment]
Another commit to cherry pick: https://github.com/facebook/react-native/commit/46c7ada535f8d87f325ccbd96c24993dd522165d

**Comment by aldistel** [comment]
And another one ;) https://github.com/facebook/react-native/pull/25150/commits/e787dd0ad614910497af05ade4f54831280ffbd6

**Comment by thymikee** [comment]
Bumping CLI: https://github.com/facebook/react-native/commit/ea090a10e63bb75ab9446ed2bd84647bf3d28bd7

**Comment by benoitdion** [comment]
what version of `jsc-android` is RN 0.60 planning to use? `241213.2.0` (currently next) fixes a family of native crashes but introduces significant performance regression. The version included with 0.59 is much faster but unfortunately crashes more frequently. 

Relevant issues:
- https://github.com/react-native-community/jsc-android-buildscripts/pull/108
- https://github.com/facebook/react-native/issues/24261

**Comment by kelset** [comment]
Hey everyone, I'm trying to cherry picks the commits & do a RC1 release. I've been hitting some pretty nasty cache-related (it seems) issues, so I'm not sure I'll be able to do the release today.

A few of the commits requested where already on branch because of the recut that happened a while ago, and I couldn't cherry pick one of the requested because it actually disappeared from master's commit history...?

Anyway, you can check the status here: https://github.com/facebook/react-native/commits/0.60-stable

I'll write an update once it's out.

**Comment by thymikee** [comment]
Take your time @kelset, it's Friday anyway :D

**Comment by kelset** [comment]
Allright, after way too many fights with the CI - but also one real issue which thanks to @thymikee we fixed right away - RC1 is finally out!

Please test it and let us know: https://github.com/facebook/react-native/releases/tag/v0.60.0-rc.1

**Comment by slestang** [comment]
I am trying to test .60.0-rc.1 on a existing project where every dependencies (more than 20) are handled with CocoaPods and `pod install` fail:

```
[!] CocoaPods could not find compatible versions for pod "React/Core":
  In Podfile:
    RNSound (from `../node_modules/react-native-sound`) was resolved to 0.10.12, which depends on
      React/Core
```

Apparently in https://github.com/facebook/react-native/commit/2321b3fd7f666ce30f5dad4cd2673ddf22972056 the core pod has been renamed from `React/Core` to `React-Core` :-(

At least 2 projects seems to be impacted: react-native-sound and rn-fetch-blob.
I didn't find a way to trick pod with an alias or something else to work-around the issue.

What is the best way to fix this? Making PR to these project with the renaming?

**Comment by Frekansapp** [comment]
After update react native version to v0.60.0-rc1. I'm facing build errors. Anyone else have this errors? https://github.com/wix/react-native-navigation/issues/5171 https://github.com/wix/react-native-camera-kit/issues/262 https://github.com/react-native-community/react-native-image-picker/issues/1095

**Comment by kelset** [comment]
@Frekansapp it really seems that the errors you are seeing are related to you updating only your version number in the package.json? Since we are still in RC phase, please don't update production apps until we reach 0.60.0 and/or there is a diff here https://github.com/react-native-community/rn-diff-purge to help you understand all the changes that you need to do.

@slestang oh wow I wasn't aware of that 😓 yeah I think that the best solution would be to do a PR to the library affected.

**Comment by sunnylqm** [comment]
@kelset And react need a re-sync or revert.  See https://github.com/facebook/react-native/issues/24512 and https://github.com/facebook/react-native/commit/b7d84747b895d8645a12d68c27c6d8a45eee8b6e

**Comment by Frekansapp** [comment]
@kelset thank you. I made the necessary changes according to rn-diff-purge but now i'm getting another error you can see here https://paste.ubuntu.com/p/SwSgWKtBNV/ how can i solve this?

**Comment by matt-oakes** [comment]
@Frekansapp You have an Android dependency which has not been upgraded to AndroidX. To use 0.60 all libraries need to be migrated to AndroidX. This is obviously a blocker at the minute, but there's a discussion over here where we are trying to find a good solution:

https://github.com/react-native-community/discussions-and-proposals/issues/129

It seems like for you, it's `react-native-maps` that needs to be migrated to AndroidX.

**Comment by jobpaardekooper** [comment]
I think the change "Enable views to be nested within Text component" is not working properly. The following code does not work. Keep in mind that this specific code is clearly redundant but illustrates the issue clearly.

```
<Text>
    <View>
        <Text>Hello world!</Text>
    </View>
</Text>
```

The code above does not display anything on the screen.
Tested with 0.60.0 RC1.

**Comment by tamirrab** [comment]
https://github.com/react-native-community/releases/issues/116#issuecomment-500732698

Tested too
Not showing the text

**Comment by sparker-mob** [comment]
Hi,
The bug for App Crash on certain Android devices like Samsung S7, still exists for this RN version.
Reference : https://github.com/facebook/react-native/issues/24261

This crash also happens if we generate a fresh new React Native project using React Native CLI and run it on Android device like Samsung S7. The crash happens if you launch the App, and keep on tapping on the screen for few seconds. The crash logs are the same as attached on the above bug link.

Do we have an estimate as to when this issue would be resolved and in which RN version? As highlighted in the link, this is a High Priority issue to be solved before Android makes 64-bit a mandate starting August 2019 (https://developer.android.com/distribute/best-practices/develop/64-bit)

**Comment by tido64** [comment]
> And another one ;) [facebook/react-native@e787dd0](https://github.com/facebook/react-native/commit/e787dd0ad614910497af05ade4f54831280ffbd6)

@kelset Looks like this got moved: https://github.com/facebook/react-native/commit/2dd7dd8e45f9d4a1086f84d5b70ea66406d98439. Can we get it into 0.60 please? :)

cc @aldistel

**Comment by armata007** [comment]
Hi,
after creating new project with "react-native init RN060 --version react-native@next" (which installs rc1) and running "react-native run-android" 
I get
`error ● Validation Error:

  Option "server.port" must be of type:
    number
  but instead received:
    string

  Example:
  {
    "port": 8080
  }`

I don't have this issue on rc0. I think it should work out of the box for new projects.

After adding
server: { port: 8081 } to metro config this error disappears but I get
"Failed to construct transformer:  Error: Option 'mapper' isn't supported by the Node crawler" which I do not know how to fix

**Comment by thymikee** [comment]
@armata007 it's a known issue, we working on it. In the meantime you can use Yarn `resolutions` and pin `@react-native-community/cli` to version `2.0.0-rc.2`

**Comment by jobpaardekooper** [comment]
@armata007 
You can also open a new terminal window.
Navigate to your RN060 folder.
Run `react-native start`.
Wait for the server to start.
Press the reload button on the simulator.

**Comment by Kennytian** [comment]
@armata007 @thymikee 
open `node_modules/jest-haste-map/build/crawlers/node.js`, go to line 226, and then remove
```javascript
if (options.mapper) {
  throw new Error(`Option 'mapper' isn't supported by the Node crawler`);
}
```

references: https://github.com/facebook/jest/pull/8558/files#diff-a8d4602cd89511c26bc2fb165f65379aL143

**Comment by thymikee** [comment]
@Kennytian for this all you need to do now is purging `jest-haste-map` entry in a lockfile, so it resolves to 24.8.1 after re-install

**Comment by annakocheshkova** [comment]
> @IljaDaderko @immortalx It's an opt-in feature on both platforms. For iOS you need to add these two lines to your `ios/Podfile`: [facebook/react-native@261197d#diff-a3c6c8e64fbbd1efef345c45e3811571](https://github.com/facebook/react-native/commit/261197d85705dad1a362cc4637aa308c0382dcbe#diff-a3c6c8e64fbbd1efef345c45e3811571)
> 
> Note that these are currently not in the template `Podfile` due to an issue with the E2E CI tests.

Hi, I'm trying to test this with my plugin, I can't seem to get at what stage and how this should work? I have my plugin with the <my_plugin.podspec> at the root folder, how it's supposed to be picked up by react-native and when? I see that it is installed if I run `pod install` manually, but my dependency is never added to the Podfile...  @matt-oakes @thymikee

**Comment by kelset** [comment]
> how it's supposed to be picked up by react-native and when?
AFAIK, it should be "picked up" when you do `yarn add NAME_OF_LIBRARY`.

**Comment by netdown** [comment]
I was trying to create a new app with a basic setup consisting of react-redux and react-navigation, literally nothing just initializing these with one page. Got a "callback is not a function" error (I saw the screen loading for half second though) and the stacktrace consisted of react-native source files only. It may be similar to [#15647](https://github.com/facebook/react/issues/15647) as installing scheduler 0.14.0 also solved this. I attached the stacktrace.
![Screenshot_2019-06-14-16-11-33-971_com rn060](https://user-images.githubusercontent.com/4265403/59515699-fb729900-8ebf-11e9-85a4-7d2d5d5e6ad6.png)
![Screenshot_2019-06-14-16-11-37-288_com rn060](https://user-images.githubusercontent.com/4265403/59515700-fb729900-8ebf-11e9-8292-c29eb2e2a493.png)

**Comment by annakocheshkova** [comment]
@kelset it doesn't. I could open an issue but it just seems like I'm missing something important.

**Comment by thymikee** [comment]
@annakocheshkova 
> I see that it is picked up if I run pod install manually, but my dependency is never added to the Podfile and even after that, the project doesn't build...

That's how autolinking works -> it doesn't touch Podfile (but Podfile.lock will be created if you use it) nor Gradle, but automatically generate stuff based on `dependencies` and `devDependencies` in package.json. If you use local plugins, I think it's not currently supported to autolink and you'd need to link them traditionally. Is this your use case?

**Comment by annakocheshkova** [comment]
@thymikee to test, I change my plugin locally, yes. I then run `yarn add ../path-to-plugin`.
Previously our postlink script added an entry to user's `Podfile` which was then installed. Now I moved `podspec` to the root - is this enough in order for autolink to work with a "real" (non-local) plugin?

Another question I have is - we still have a postlink script which does some additional setup for our plugin. I moved rnpm configuration to r`eat-native.config.js` and whatever's in the postlink script gets executed if I manually call `react-native link`. But should this also be executed automatically?

**Comment by thymikee** [comment]
> Now I moved podspec to the root - is this enough in order for autolink to work with a "real" (non-local) plugin 

That should be enough. 

Regarding pre/postlink hooks, this is not yet supported with autolinking unfortunately. That's because the linking logic moved to CocoaPods and Gradle scripts, but I think we should be able to support that. Created a related feature request in CLI: https://github.com/react-native-community/cli/issues/429

**Comment by theolavaux** [comment]
I found a bug where TextInput `color` prop cannot be used along SecureTextInput.
Could this be solved in the release?

**Comment by adeteejay** [comment]
Hi guys, I'm not sure if this is where to ask, but does this mean from .60+ cocoapods will be required in all projects? Can those who use/prefer Carthage stick to it?

**Comment by thymikee** [comment]
It's not required, it will be the default though.

**Comment by MohamadKh75** [comment]
Hey

Can we have this please?

https://github.com/facebook/react-native/commit/d9a8ac5071d23275c5d4a8e9936f391b967416d7

**Comment by kelset** [comment]
Hey everyone, we are looking into having a new RC2 with a couple more commits in the next few days.

@theolavaux the issue you linked should be fixed via a PR whose commit is already in RC1, can you test it and see if it still appears on a project using 0.60-rc1? If it's still there, please write a comment in the issue.

@sparker-mob it seems that Kudo released a new version of JSC which [solves the crashes](https://github.com/facebook/react-native/issues/24261#issuecomment-498682537), please refer to that.

@jobpaardekooper @tamirrab was it working for you in 0.60-rc0? Also, can you please post an issue in the main repo?

**Comment by jobpaardekooper** [comment]
@kelset it isn't working on 0.60-rc0 and 0.60-rc1.

I opened an issue in the main repo a little bit ago: #25197.

**Comment by benoitdion** [comment]
@kelset can you confirm whether 0.60 will point to Kudo's JSC release? As mentioned in https://github.com/react-native-community/releases/issues/116#issuecomment-499859207, it helps with the crash but impacts performance significantly.

**Comment by german970814** [comment]
Is there any updates about this issue #23021 and #24055

**Comment by Kudo** [comment]
@benoitdion JSC in 0.60 would be the same as 0.59. (Only a minor difference that removed libc++_shared.so)
As JSC in the meantime does not have balance between performance and crash free and  we are not going to push new version.
However, for RN 0.60, you could simply use `yarn add jsc-android@next` to use different JSC than the builtin one in RN. (Yeah, just a single command)

**Comment by jemmyphan** [comment]
@Kudo does removing libc++_shared.so solve the crash issue?
about a  few days ago I saw your tweet about experimenting on v8.
does it work well?

**Comment by kelset** [comment]
@jemmyphan 	please keep this issue on topic ;)

@german970814 sorry, I don't have any - if there are updates on them, they will get communicated in the issues themselves. Maybe what you could do is to test them both with the latest RC and report if the issues are still present.

I'll try to set the RC2 later today, aiming for 0.60.0 next week if nothing major pops up.

**Comment by dulmandakh** [comment]
I'm using 0.60.0-rc.1 and useEffect hook is causing error, and here is a solution https://github.com/facebook/react/issues/15647#issuecomment-492419380. IMHO, we should fix this before stable release

**Comment by kelset** [comment]
It seems that Dan did that on master: https://github.com/facebook/react/issues/15647#issuecomment-492319651

Can you help me find the commit in which it happens so that I can cherry pick it?

**Comment by robertying** [comment]
@kelset this one https://github.com/facebook/react-native/commit/3b1dbccaaf90aa05a0b25e4853e6b8d48da1deaf

**Comment by kelset** [comment]
It was actually this one ;) https://github.com/facebook/react-native/commit/6001acb319958242f8d8e2dd40cb91a55b5eab2e

I'm not sure I need to cherry-pick the other one

**Comment by robertying** [comment]
@kelset oh yeah 😅 sorry I opened two tabs and copied the other wrong commit. Yours is correct.

**Comment by kelset** [comment]
No worries :) I'll try to do the cherry-picks & test them today 🤞

**Comment by kelset** [comment]
Ok quick update: I've managed to cherry pick

* https://github.com/facebook/react-native/commit/2dd7dd8e45f9d4a1086f84d5b70ea66406d98439
* https://github.com/facebook/react-native/commit/6c0eccd46d157804fde767263ec8856ff8c99cfb

and

* https://github.com/facebook/react-native/commit/261197d85705dad1a362cc4637aa308c0382dcbe (which should bring back the full autolink feature for iOS - and now both platforms should then "use it")

The other two commits:

* https://github.com/facebook/react-native/commit/6001acb319958242f8d8e2dd40cb91a55b5eab2e

* https://github.com/facebook/react-native/commit/d9a8ac5071d23275c5d4a8e9936f391b967416d7

were already in the branch.

Which leads me two a good news and a bad news:
* my test with these cherry-picks went ✅
* the issue with the scheduler version is *not* actually fixed, and we are talking with the FB engineers to come up with a solution. But it's likely that it will need to use a yarn resolution in the package.json.

I will not release the RC2 until I know what we will do about the scheduler thing, I'll update here asap.

**Comment by kelset** [comment]
Hey everyone! Thanks to the help of @rickhanlonii we found a solution for the scheduler for RC2, and now [RC2](https://github.com/facebook/react-native/releases/tag/v0.60.0-rc.2) is out 🚀

This will *likely* be the last RC before 0.60.0, unless something huge bubbles up. So please, test it and let us know if you have any regressions 🤗

(as always, please open an issue in the main repo & just post here a link so that we can keep track of the conversation more easily!)

**Comment by robertying** [comment]
Hey @kelset I've had this possible regression issue https://github.com/facebook/react-native/issues/25325. Would you mind taking a look?

**Comment by JonnyBurger** [comment]
I get an issue with context.

React Navigation's `withNavigator` HOC is suddenly not working anymore which is suspicious.

Made an issue with repro here: https://github.com/facebook/react-native/issues/25337

**Comment by mikehardy** [comment]
@kelset thanks for the patience on the regression @robertying found (and fixed)  :muscle: when this PR lands it fixes things https://github.com/facebook/react-native/pull/25363

**Comment by kelset** [comment]
Hey everyone, it seems that that extra feature will not land in the end.

But since we have a few Android commits that needs to be cherry picked:
* https://github.com/facebook/react-native/commit/3915c0fa6178fbb8aa9b8bd54881cfdbde8fde70
* https://github.com/facebook/react-native/pull/25358
* https://github.com/facebook/react-native/commit/58beaf02ec1c55647eaec965ee5999f591c6c0d3

I'll probably still do a RC3 first this week.

**Comment by doublex** [comment]
Could you apply https://github.com/facebook/react-native/commit/690e85db0487c10ec3880c503632548aca65ff1c in 0.60?

**Comment by kelset** [comment]
Hey everyone - quick update. By end of this week I'm expecting a couple of PRs to land that we want to cherry pick:
- a bump to the CLI to rc3
- an update for the JSC which should solve most of the issues related to Android 64b builds

And there is a small chance that we'll have a fix for the `use_frameworks!` pod config.
We'll do a RC3 when those two commits land, and likely 0.60.0 will be the release after.

**Comment by muditpant13** [comment]
@kelset When is the expected release date for 0.60 ? Thanks..

**Comment by Warmachine13** [comment]
hey guys i have this problem on init project eslint@6.0.1: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "11.8.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
(node:6480) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add -D @babel/core @babel/runtime @react-native-community/eslint-config eslint jest babel-jest metro-react-native-babel-preset react-test-renderer@16.8.6
    at makeError (C:\Users\Cliente\Documents\RN060\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Users\Cliente\Documents\RN060\node_modules\execa\index.js:278:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:6480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nicoburns** [comment]
@warmachine13 You need to upgrade your node version to 11.10.1 or higher.

**Comment by kadikraman** [comment]
@Warmachine13 - as the error says, upgrade your node version, e.g. `nvm install 11.10.1`

**Comment by kelset** [comment]
Hey everyone 👋

I just finished cherry picking + testing the commits above, plus the ones described (bump to CLI RC & JSC for Android) - it should be rolling out any minute now.

For the iOS `use_framework!` issue there is a PR in the work but it will likely not be ready in time when we want to release 0.60.0.

In the meantime, please test RC3 and report if you are seeing any massive issues via opening an issue in the main repo & posting the link here!

**Comment by Kennytian** [comment]
Couldn't find any versions for "@react-native-community/cli" that matches "2.0.0-rc.3"
? Please choose a version of "@react-native-community/cli" from this list: (Use arrow keys)

**Comment by thymikee** [comment]
@Kennytian it's there:https://www.npmjs.com/package/@react-native-community/cli/v/2.0.0-rc.3, so maybe that's an issue with the cache of your package manager.

**Comment by Kennytian** [comment]
@thymikee  Thanks for your fast response. It's my fault, used the mirror npm source.

**Comment by brunolemos** [comment]
`ItemSeparatorComponent's ` fix to cherry pick: https://github.com/facebook/react-native/commit/1e428093e2d959d415e228b1c0e12ddd569aff89

**Comment by thymikee** [comment]
https://github.com/facebook/react-native/commit/44c05da0ff558ab25d9c91c50c77c62c9efd8da3

**Comment by RoJoHub** [comment]
Could you apply  facebook/react-native@fb550e9

**Comment by auchaphon** [comment]
Include facebook/react-native@76c50c1 Please

**Comment by kelset** [comment]
👋 everyone!

Thanks for the latest feedback, I just pushed the commit to trigger the release for 0.60.0 - let's close this and see you in the cherry pick request issue -> https://github.com/react-native-community/releases/issues/130

**Comment by cbpanchal** [comment]
@grabbou Please check, react-native version 0.60.4 run android stuck and it takes too much time to compile. help me to short out
![npx__Users_chirag_Workspace_Upgrade_App_CrushClient_and_PreviewItem_js_—_CrushClient](https://user-images.githubusercontent.com/20139279/62613052-548e0480-b926-11e9-9b0e-f5660cd60343.png)

Thanks
